version: '3.5'

services:
  kernel:
    build:
      context: ./
    image: vivasa/ubuntu:kernel
  ubuntu:
    build:
      context: ./ubuntu
      dockerfile: ./Dockerfile
    image: vivasa/ubuntu:learn
    container_name: ubuntum
    hostname: ubuntum
    environment:
      TERM: xterm-256color
    ports:
      - "80"
    tty: true
