version: '3.5'

services:
  vibuntu:
    image: vivasa/ubuntu:learn
    container_name: vibuntu
    hostname: vibuntu
    environment:
      TERM: xterm-256color
    command: /root/config/state2/launch.sh
    volumes:
      - ${WORK_DIR}:/root/sources
    ports:
      - "80"
    tty: true